import pic from "../assets/png/profile.jpg"
interface briefDatas {
  name: string;
  sector: string;
  price: string;
  desc: string;
  rate: string;
  image: any;
  location: string;
}

export const BriefData: any = [
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
  },
];

export const EmploymentData: any = [
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
  {
    name: "Daniel",
    sector: "Oil and Gas",
    price: " ₦100,00.00",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    year: "Year of Call: 2013",
  },
];
export const JobsData: any = [
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
  {
    company: "Quantum Incorporation",
    sector: "Oil and Gas",
    location: "Lagos, Nigeria",
    desc: "Lorem ipsum dolor sit amet, consect adipiscing elit. Lorem ipsum dolor sit amet, consect adipiscing elit. ",
    rate: "4.5(10)",
    image: pic,
    jobType: "Full-time role",
  },
];
 