import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "./ContextProvider";
const inter = Inter({ subsets: ["latin"] });
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Sportrex NFT Marketplace",
  description: "Explore the best NFTs on Sportrex.",
  openGraph: {
    title: "Sportrex NFT Marketplace",
    description: "Explore the best NFTs on Sportrex.",
    url: "https://sportrex-marketplace-18bv.vercel.app",
    images: [
      "https://army-barrack.vercel.app/static/media/soldier-asset-1.e32781844491acdf5400660b848ad420.svg",
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Sportrex NFT Marketplace",
    description: "Check out this amazing NFT!",
    images: [
      "https://army-barrack.vercel.app/static/media/soldier-asset-1.e32781844491acdf5400660b848ad420.svg",
    ],
  },
};
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
